### ===========================================
### SERWIS 3: UŻYTKOWNICY (Port 3003)
### ===========================================

####################################
# Sign up
####################################
POST http://localhost:3003/api/register
Content-Type: application/json

{
    "email": "antoni@kowalski.pl",
    "password": "xdxd123"
}

####################################
# Sign in
####################################
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "email": "antoni@kowalski.pl",
    "password": "xdxd123"
}


####################################
# User Token
####################################
@token = eyJhGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJhbnRvbmlAa293YWxza2kucGwiLCJpYXQiOjE3Njc4ODIxMTMsImV4cCI6MTc2Nzg4NTcxM30.o4o0ji03RbNth5OlOhxBAtub-977BQ5v_yZrOjdVAF0

####################################
# Get all books
####################################
GET http://localhost:3001/api/books

####################################
# Add book
####################################
POST http://localhost:3001/api/books
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Trylogia cz.2: Potop",
    "author": "Henryk Sienkiewicz",
    "year": 1886,
}

####################################
# Add Post
####################################
POST http://localhost:3002/api/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userId": 1,
    "bookId": 77771,
    "quantity": 7
}

####################################
# Get posts
####################################
GET http://localhost:3002/api/orders/1